### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by beikege**

### CODE REVIEW

**Comment by rodrigocfd** [comment]
So, what's the change here?

**Comment by beikege** [comment]
Fix syntax errors
```
.\main.go:34:5: syntax error: unexpected }, expecting expression
.\main.go:55:38: method has no receiver
.\main.go:55:38: syntax error: unexpected {, expecting name or (
```

**Comment by beikege** [comment]
Sorry, I don't know how to do it, I don't know how to use git, you already know the syntax error, my purpose is achieved.

**Comment by rodrigocfd** [comment]
No problem, it's fixed now.

Thank you.

**Pull request closed without merging**
